import React, { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../Components";
import { useDispatch,useSelector } from "react-redux";
import { getAllPosts,handleSearch } from "../Redux/postsSlice";
import { useRef } from "react";
import RenderCards from "../Components/RenderCards";
const Home = () => {
  const dispatch = useDispatch()
  const {allPosts,searchText,searchResult,loading} = useSelector(state=>state.post)
  useEffect(() => {
    dispatch(getAllPosts())
  }, [dispatch]);
  return (
    <section className="max-w-7xl mx-auto ">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by our Image Generator
        </p>
      </div>
      <div className="mt-16 ">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handleChange={(e)=>dispatch(handleSearch(e.target.value))}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for &nbsp;
                <span className="text-[222328]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchResult}
                  title="No search results found"
                />
              ) : (
                <RenderCards data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
